version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_SERVER=${DB_SERVER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PATH="/app/.venv/bin:$PATH"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
    - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:


